stages:
  - test

node-4:
  stage: test
  image: node:4
  services:
    - name: cnadiminti/dynamodb-local
      alias: dynamodb
  variables:
    NODE_ENV: test
    DATA_DIR: ./test/data
    AWS_ACCESS_KEY_ID: x
    AWS_SECRET_ACCESS_KEY: x
    AWS_DYNAMODB_REGION: us-east-1
    AWS_DYNAMODB_ENDPOINT: http://dynamodb:8000
  before_script:
    - npm install && npm rebuild
  script:
    - npm test
  cache:
    paths:
      - node_modules/

node-6:
  stage: test
  image: node:6
  services:
    - name: cnadiminti/dynamodb-local
      alias: dynamodb
  variables:
    NODE_ENV: test
    DATA_DIR: ./test/data
    AWS_DYNAMODB_ENDPOINT: http://dynamodb:8000
  before_script:
    - npm install && npm rebuild
  script:
    - npm test
  cache:
    paths:
      - node_modules/

node-8:
  stage: test
  image: node:8
  services:
    - name: cnadiminti/dynamodb-local
      alias: dynamodb
  variables:
    NODE_ENV: test
    DATA_DIR: ./test/data
    AWS_ACCESS_KEY_ID: x
    AWS_SECRET_ACCESS_KEY: x
    AWS_DYNAMODB_REGION: us-east-1
    AWS_DYNAMODB_ENDPOINT: http://dynamodb:8000
  before_script:
    - npm install && npm rebuild
  script:
    - npm test
  cache:
    paths:
      - node_modules/
